[package]
name = "serde-prost-types"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.8"
prost-types = "0.8"
serde = { version = "1.0", features = ["derive"] }
