services:
  kong:
    build: .
    ports:
      - '8000:8000'
      - '8001:8001'
    environment:
      - KONG_LOG_LEVEL=info
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./kong.conf:/etc/kong/kong.conf
      - ./kong.yml:/etc/kong/kong.yml
