[package]
name = "kong-rust-pdk"
version = "0.1.0"
authors = ["jgram <jgramoll@gmail.com>"]
edition = "2018"

[dependencies]
serde-prost-types = { path = "../serde-prost-types" }

tonic = "0.5"
prost = "0.8"
prost-types = "0.8"
tarpc = { version = "0.26", features = ["full"] }
tokio = { version = "1.11", features = ["macros", "net", "rt-multi-thread"] }
tokio-util = "0.6"
tokio-serde = { version = "0.8", features = ["json"] }
futures = "0.3"
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.5"
