[package]
name = "kong-rust-pdk-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kong-rust-pdk = { path = "../kong-rust-pdk" }
url = "2.2"

[dev-dependencies]
tokio = "1.12"
serde = "1.0"
